openapi: 3.1.0
info:
  title: Syquence API
  version: '1.0'
  description: Documentation for the Syquence API - a Symfony math sequence generator.
  contact:
    name: Andrei Ostrovskii
    email: ostrovskiime@gmail.com
    url: https://ostrovskii.me
servers:
  - url: https://syquence.ddev.site/api
    description: Local
paths:
  /auth:
    post:
      summary: Authenticate
      operationId: auth-token
      description: |
        Returns the JWT token to be used in requests to endpoints requiring authorization.
      responses:
        '200':
          description: Success.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/token'
        '400':
          $ref: '#/components/responses/400'
        '401':
          description: Unauthorized.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
              examples:
                example:
                  value:
                    message: Invalid credentials.
        '405':
          $ref: '#/components/responses/405'
        '500':
          $ref: '#/components/responses/500'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
            examples:
              example:
                value:
                  username: chuck
                  password: norris
      tags:
        - Authentication
  /sequences:
    get:
      summary: Get all supported sequences
      operationId: sequences-get
      description: |
        Returns the normalised collection of all currently supported sequences.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Returns the current high-score of the user.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/sequences'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '405':
          $ref: '#/components/responses/405'
        '500':
          $ref: '#/components/responses/500'
      tags:
        - Sequences
  /sequences/arithmetic:
    post:
      summary: Generate the arithmetic progression
      operationId: sequences-arithmetic-generate
      description: |
        Returns the arithmetic progression based on provided parameters.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Success.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/arithmetic'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '405':
          $ref: '#/components/responses/405'
        '422':
          $ref: '#/components/responses/422'
        '500':
          $ref: '#/components/responses/500'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                start:
                  type: number
                  description: int or float
                increment:
                  type: number
                  description: int or float
                size:
                  type: integer
              required:
                - start
                - increment
                - size
            examples:
              example:
                value:
                  start: 1
                  increment: 1
                  size: 5
      tags:
        - Sequences
  /sequences/geometric:
    post:
      summary: Generate the geometric progression
      operationId: sequences-geometric-generate
      description: |
        Returns the geometric progression based on provided parameters.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Success.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/geometric'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '405':
          $ref: '#/components/responses/405'
        '422':
          $ref: '#/components/responses/422'
        '500':
          $ref: '#/components/responses/500'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                start:
                  type: number
                  description: int or float
                ratio:
                  type: number
                  description: int or float
                size:
                  type: integer
              required:
                - start
                - ratio
                - size
            examples:
              example:
                value:
                  start: 1
                  ratio: 2
                  size: 5
      tags:
        - Sequences
  /sequences/fibonacci:
    post:
      summary: Generate the Fibonacci sequence
      operationId: sequences-fibonacci-generate
      description: |
        Returns the Fibonacci sequence based on provided parameters.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Success.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/fibonacci'
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '405':
          $ref: '#/components/responses/405'
        '422':
          $ref: '#/components/responses/422'
        '500':
          $ref: '#/components/responses/500'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                size:
                  type: integer
              required:
                - size
            examples:
              example:
                value:
                  size: 10
      tags:
        - Sequences
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        Go to [Authenticate](auth-token) and send the request or check 
        out README to learn how to generate the token for testing purposes.
  responses:
    '400':
      description: Bad request.
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: string
          examples:
            example:
              value:
                detail: Bad request.
    '401':
      description: Unauthorized.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
          examples:
            example:
              value:
                message: Invalid JWT Token.
    '405':
      description: Method not allowed.
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: string
          examples:
            example:
              value:
                detail: Method not allowed.
    '422':
      description: Invalid request (e.g. validation errors).
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: object
                description: Validation errors
            required:
              - error
          examples:
            example:
              value:
                error:
                  size:
                    - This value should be of type int.
    '500':
      description: Internal server error.
      content:
        application/json:
          schema:
            type: object
            properties:
              detail:
                type: string
          examples:
            example:
              value:
                detail: Internal server error.
  schemas:
    token:
      title: Authentication token
      type: object
      examples:
        - token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MjgwMzA4NjYsImV4cCI6MTcyODAzNDQ2Niwicm9sZXMiOlsiUk9MRV9BUElfVVNFUiJdLCJ1c2VybmFtZSI6ImNodWNrIn0.pg4Xxemv6rfjdWnhdwl-Nf5wvZDnitoAqSnJbYiGlZmmr1cyqL8qouGdg5mEOyWgU_MzwYclFkjKSBWjxaXgfJG22_u8lrcZ7behq9wqNcN_40aypB1RS-7zdu3RiJFhGwISggEEYegAGguY9VwFlfCWjJUHD7XUtZdRCajbhraGMXLr2x0V12XT6ZemaySgPt-6nU4_-YNi_P2kGjog1G8z1QvSSE5712gxELHZYbcPkI4ZyHCBU4md-HOt5yOf5zy9_4JdyFgig4X-qBwcbowa6S6RAtPKqNcXMA5JH4a61iGpOqAOMq99I82v1plHnvenZE_KQmgCNDDV_ffnLQ
      additionalProperties: false
      properties:
        token:
          type: string
      required:
        - token
    sequences:
      title: Sequences
      type: object
      examples:
        - data:
            arithmetic:
              id: arithmetic
              title: Arithmetic progression
            geometric:
              id: geometric
              title: Geometric progression
            fibonacci:
              id: fibonacci
              title: Fibonacci sequence
      additionalProperties: false
      properties:
        data:
          type: object
          properties:
            arithmetic:
              type: object
              properties:
                id:
                  type: string
                title:
                  type: string
              required:
                - id
                - title
            geometric:
              type: object
              properties:
                id:
                  type: string
                title:
                  type: string
              required:
                - id
                - title
            fibonacci:
              type: object
              properties:
                id:
                  type: string
                title:
                  type: string
              required:
                - id
                - title
      required:
        - data
    arithmetic:
      title: Arithmetic progression
      type: object
      examples:
        - data:
            - 1
            - 2
            - 3
            - 4
            - 5
      additionalProperties: false
      properties:
        data:
          type: array
      required:
        - data
    geometric:
      title: Geometric progression
      type: object
      examples:
        - data:
            - 1
            - 2
            - 4
            - 8
            - 16
      additionalProperties: false
      properties:
        data:
          type: array
      required:
        - data
    fibonacci:
      title: Fibonacci sequence
      type: object
      examples:
        - data:
            - 0
            - 1
            - 1
            - 2
            - 3
            - 5
            - 8
            - 13
            - 21
            - 34
      additionalProperties: false
      properties:
        data:
          type: array
      required:
        - data
